language: cpp

branches:
  except:
    - master
    - lfg

compiler:
  - gcc
  - clang

script:
  - test -d _build || mkdir _build
  - test -d _install || mkdir _install
  - cd _build
  - cmake -DPREFIX=../_install ..
  - make -j4
